### ISSUE TITLE
Add permalinks for questions

### ISSUE THREAD

**Issue by kkomelin** [psavinov/spain-answer#2]
## Problem/Motivation

When someone asks you a question you answered many times before and this question is already in the database, you want to just send a direct link to the answer. The person you would send such link, might be willing to share the link with their friends.
I don't think it's currently possible.

## Proposed Resolution

Add a permanent link for each question, and a way for you to quickly get it and send to people.

**Comment by psavinov** [comment]
@kkomelin Finally resolved :) thanks a lot for the idea!

**Comment by kkomelin** [comment]
I've just tested it. Very useful! Thanks @psavinov!
